#ifndef _DOS_VIDEO_H_
#define _DOS_VIDEO_H_

#include <stdint.h>
#include <stdbool.h>

/* MS-DOS core video layer.
 *
 * Design notes live in external/8086tiny/docs/video/. In brief:
 *
 *   - Output is LUT8, 320x240, never scaled. Guest content is 200 rows,
 *     centred with 20 blank rows top and bottom. Those bars are reserved for
 *     the on-screen keyboard and this layer never writes them except to clear
 *     on a mode change.
 *   - Mode and geometry come from the BIOS Data Area, which 8086tiny's BIOS
 *     maintains: 0x449 mode, 0x44A columns. No INT 10h hook is needed.
 *   - Column count selects the font: 80 -> 4x8, 40 -> 8x8. Both are exactly
 *     320 px wide.
 */

#define DOS_LCD_WIDTH    320
#define DOS_LCD_HEIGHT   240
#define DOS_ACTIVE_ROWS  200
#define DOS_LETTERBOX    ((DOS_LCD_HEIGHT - DOS_ACTIVE_ROWS) / 2)   /* 20 */

#define DOS_TEXT_ROWS    25

/* Generated by tools/gen_dos_font.py.
 * 4x8: low nibble used, bit 3 = leftmost pixel.
 * 8x8: full byte, bit 7 = leftmost pixel. */
extern const uint8_t dos_font_4x8[256][8];
extern const uint8_t dos_font_8x8[256][8];

/* Program the CLUT and clear both framebuffers. Call once after the LCD has
 * been switched to LUT8 mode, before the first blit. */
void dos_video_init(void);

/* Render one frame of guest video into the current framebuffer. Safe to call
 * every frame; detects mode changes itself. Handles text modes 0-3 and CGA
 * graphics modes 4/5 (320x200x2bpp) and 6 (640x200x1bpp). Hercules is out of
 * scope. */
void dos_video_blit(void);

#endif /* _DOS_VIDEO_H_ */
