/* MS-DOS core video layer -- text mode.
 *
 * Upstream 8086tiny has no graphical text mode at all: it renders only in
 * graphics modes and sends text to stdout through termios. DOS boots into text
 * mode, so this is the port's primary display path and is written from scratch.
 * See external/8086tiny/docs/video/04-text-rendering.md.
 *
 * Graphics modes (CGA 4/5/6) are a separate task and are ignored here.
 */

#include "dos_video.h"

#include "gw_lcd.h"

#include <string.h>

/* Guest memory access. dos_fold() in 8086tiny.c maps the guest's 1 MB space
 * into a 768 KB array; raw guest addresses must never index mem[] directly,
 * which is exactly what this accessor exists to prevent. */
extern unsigned char *dos_mem_ptr(unsigned int guest_addr);
extern unsigned char io_ports[];

/* ---------------------------------------------------------------------------
 * BIOS Data Area
 *
 * 8086tiny's BIOS lays out a standard BDA at segment 0x40 and maintains it on
 * every INT 10h mode set (bios_source/bios.asm:1097, :1128, declarations at
 * :3609+). Offsets verified against that declaration block.
 * ------------------------------------------------------------------------- */
#define BDA_VIDMODE      0x449   /* current video mode                      */
#define BDA_VID_COLS     0x44A   /* word: column count                      */
#define BDA_PAGE_SIZE    0x44C   /* word: bytes per page (0x1000)           */
#define BDA_CURPOS       0x450   /* 8 pages x (col, row)                    */
#define BDA_CUR_V_END    0x460   /* cursor last scanline                    */
#define BDA_CUR_V_START  0x461   /* cursor first scanline (note the order)  */
#define BDA_DISP_PAGE    0x462   /* active display page                     */
#define BDA_CRT_START    0x4AD   /* word: CRTC start address, in characters */

/* NOTE: BDA 0x484 (vid_rows) is NOT usable here. A real PC BIOS stores
 * rows-1; 8086tiny declares `vid_rows db 25` (bios.asm:3662) -- the literal
 * count, not count-1 -- and never reads it anywhere. Treating it as rows-1
 * would render 26 rows. We use the fixed 25 the BIOS actually implements. */

#define CGA_MODE_CTRL    0x3D8   /* bit 5: blink enable                     */
#define CGA_BLINK_ENABLE 0x20

#define TEXT_VRAM_BASE   0xB8000 /* guest address of colour text memory     */

/* ---------------------------------------------------------------------------
 * Palette
 *
 * Exactly 32 entries are declared, never 16. LCD_DARKEN_BIT is fixed at +32
 * (gw_lcd.h:169) but lcd_set_clut() writes darkened twins at count+i
 * (gw_lcd.c:455); those agree only when count == 32. Declaring 16 would leave
 * the twins at [16..32) while the darken path reads [32..48), so dimming the
 * screen behind a Retro-Go menu would show black instead of a dimmed image.
 *
 * CGA's 16 colours occupy [0..16); [16..32) mirrors them so the block is full
 * and any stray high index still resolves to something sane.
 * ------------------------------------------------------------------------- */
#define DOS_CLUT_COUNT 32

static const uint32_t cga_palette[16] = {
    0x000000, 0x0000AA, 0x00AA00, 0x00AAAA,
    0xAA0000, 0xAA00AA, 0xAA5500, 0xAAAAAA,
    0x555555, 0x5555FF, 0x55FF55, 0x55FFFF,
    0xFF5555, 0xFF55FF, 0xFFFF55, 0xFFFFFF,
};

/* ---------------------------------------------------------------------------
 * Row expansion
 *
 * Turns a 4-bit glyph row into four bytes of 0x00/0xFF mask, so a glyph row
 * becomes one 32-bit store instead of four byte stores plus branches:
 *
 *     word = (mask & fg_word) | (~mask & bg_word)
 *
 * Byte 0 of the word is the leftmost pixel. The core is little-endian, so byte
 * 0 sits in the low 8 bits. Nibble bit 3 is the leftmost pixel, matching the
 * font tables generated by tools/gen_dos_font.py.
 *
 * The same table serves the 8x8 font: its high nibble expands to pixels 0-3
 * and its low nibble to pixels 4-7.
 * ------------------------------------------------------------------------- */
static uint32_t expand4[16];

static void build_expand_table(void)
{
    for (unsigned n = 0; n < 16; n++) {
        uint32_t w = 0;
        for (unsigned x = 0; x < 4; x++) {
            if (n & (1u << (3 - x)))
                w |= 0xFFu << (8 * x);
        }
        expand4[n] = w;
    }
}

/* Replicate a CLUT index across four bytes. */
static inline uint32_t splat(uint8_t idx)
{
    return (uint32_t)idx * 0x01010101u;
}

/* ---------------------------------------------------------------------------
 * State
 * ------------------------------------------------------------------------- */
static uint8_t  last_mode  = 0xFF;
static uint16_t last_cols  = 0;
static bool     initialised = false;

static inline uint16_t bda16(unsigned addr)
{
    const unsigned char *p = dos_mem_ptr(addr);
    return (uint16_t)(p[0] | (p[1] << 8));
}

static inline uint8_t bda8(unsigned addr)
{
    return *dos_mem_ptr(addr);
}

static void clear_framebuffers(void)
{
    /* Clears the letterbox bars too. Video owns clearing them on a mode change;
     * it must not write them at any other time -- they belong to the on-screen
     * keyboard (docs/video/06-framebuffer-clut.md). Both buffers are cleared so
     * bar content cannot flicker at the swap rate. */
    memset(lcd_get_active_buffer(),   0, DOS_LCD_WIDTH * DOS_LCD_HEIGHT);
    memset(lcd_get_inactive_buffer(), 0, DOS_LCD_WIDTH * DOS_LCD_HEIGHT);
}

void dos_video_init(void)
{
    build_expand_table();

    uint32_t clut[DOS_CLUT_COUNT];
    for (unsigned i = 0; i < DOS_CLUT_COUNT; i++)
        clut[i] = cga_palette[i & 15];
    lcd_set_clut(clut, DOS_CLUT_COUNT);

    clear_framebuffers();

    last_mode = 0xFF;
    last_cols = 0;
    initialised = true;
}

/* ---------------------------------------------------------------------------
 * Text rendering
 * ------------------------------------------------------------------------- */
static void blit_text(uint8_t *fb, uint16_t cols)
{
    const uint8_t (*font)[8] = (cols >= 80) ? dos_font_4x8 : dos_font_8x8;
    const unsigned cell_w    = (cols >= 80) ? 4 : 8;
    const bool     narrow    = (cols >= 80);

    /* Page and CRTC start. Software scrolls by moving the start address rather
     * than moving 4 KB of memory, so ignoring it renders a static view. In text
     * mode the value is in *character* units, hence the *2. */
    unsigned page       = bda8(BDA_DISP_PAGE) & 7;
    unsigned page_size  = bda16(BDA_PAGE_SIZE);
    if (page_size == 0)
        page_size = 0x1000;
    unsigned start_char = bda16(BDA_CRT_START);

    /* Colour text memory is the 32 KB window at 0xB8000-0xBFFFF. Wrap the page
     * and start-address offset inside it: both come from guest-writable BDA
     * fields, and an out-of-range value would otherwise fold to the scratch
     * page and render garbage rather than wrapping like real hardware. */
    unsigned offset = (page * page_size + start_char * 2) & 0x7FFF;
    unsigned base   = TEXT_VRAM_BASE + offset;

    const bool blink_enabled = (io_ports[CGA_MODE_CTRL] & CGA_BLINK_ENABLE) != 0;

    /* ~1.9 Hz: the CGA divides vertical refresh by 16, giving 16 frames on and
     * 16 off at 60 Hz, which is bit 4 of the frame counter. */
    const bool blink_on = (lcd_get_frame_counter() & 0x10) != 0;

    uint8_t *dst_top = fb + DOS_LETTERBOX * DOS_LCD_WIDTH;

    for (unsigned row = 0; row < DOS_TEXT_ROWS; row++) {
        const unsigned char *cell = dos_mem_ptr(base + row * cols * 2);
        uint8_t *dst_row = dst_top + row * 8 * DOS_LCD_WIDTH;

        for (unsigned col = 0; col < cols; col++) {
            uint8_t ch   = cell[col * 2];
            uint8_t attr = cell[col * 2 + 1];

            uint8_t fg = attr & 0x0F;
            uint8_t bg = (attr >> 4) & 0x07;

            /* Bit 7 is blink or background intensity, depending on the CGA
             * mode-control register. Software that wants 16 background colours
             * clears that bit explicitly. */
            if (blink_enabled) {
                if ((attr & 0x80) && !blink_on)
                    fg = bg;            /* blinked off: draw as background */
            } else {
                bg |= 0x08;             /* intensity promotes bg to 16 colours */
            }

            const uint32_t fgw = splat(fg);
            const uint32_t bgw = splat(bg);
            const uint8_t *glyph = font[ch];

            /* Cell origins are 4-byte aligned: rows are 320 bytes (a multiple
             * of 4), cells are 4 or 8 bytes wide, and the framebuffer base is
             * linker-aligned. The 32-bit stores below are therefore safe. */
            uint8_t *dst = dst_row + col * cell_w;

            if (narrow) {
                for (unsigned y = 0; y < 8; y++) {
                    uint32_t mask = expand4[glyph[y] & 0x0F];
                    *(uint32_t *)(dst + y * DOS_LCD_WIDTH) =
                        (mask & fgw) | (~mask & bgw);
                }
            } else {
                for (unsigned y = 0; y < 8; y++) {
                    uint8_t  g  = glyph[y];
                    uint32_t m0 = expand4[(g >> 4) & 0x0F];
                    uint32_t m1 = expand4[g & 0x0F];
                    uint32_t *p = (uint32_t *)(dst + y * DOS_LCD_WIDTH);
                    p[0] = (m0 & fgw) | (~m0 & bgw);
                    p[1] = (m1 & fgw) | (~m1 & bgw);
                }
            }
        }
    }

    /* Cursor. Shape comes from BDA 0x460 (end) / 0x461 (start) -- reversed
     * order, matching real hardware and bios.asm:3646-3647. start > end means
     * the cursor is HIDDEN, which is how software turns it off; treating it as
     * an inverted range would paint a block over the character instead. */
    uint8_t c_end   = bda8(BDA_CUR_V_END);
    uint8_t c_start = bda8(BDA_CUR_V_START);

    if (c_start <= c_end && c_start < 8 && blink_on) {
        unsigned cx = bda8(BDA_CURPOS + page * 2);
        unsigned cy = bda8(BDA_CURPOS + page * 2 + 1);

        if (cx < cols && cy < DOS_TEXT_ROWS) {
            const unsigned char *cell = dos_mem_ptr(base + cy * cols * 2);
            uint8_t fg = cell[cx * 2 + 1] & 0x0F;
            uint32_t fgw = splat(fg);

            uint8_t *dst = dst_top + cy * 8 * DOS_LCD_WIDTH + cx * cell_w;
            unsigned y_end = (c_end < 7) ? c_end : 7;

            for (unsigned y = c_start; y <= y_end; y++) {
                uint32_t *p = (uint32_t *)(dst + y * DOS_LCD_WIDTH);
                p[0] = fgw;
                if (!narrow)
                    p[1] = fgw;
            }
        }
    }
}

/* ---------------------------------------------------------------------------
 * Entry point
 * ------------------------------------------------------------------------- */
void dos_video_blit(void)
{
    if (!initialised)
        dos_video_init();

    /* The CLUT and framebuffer layout only exist in LUT8 mode. */
    if (lcd_get_mode() != LCD_MODE_LUT8)
        return;

    uint8_t mode  = bda8(BDA_VIDMODE);
    uint16_t cols = bda16(BDA_VID_COLS);

    /* 80 selects the narrow font, 40 the wide one; anything else is a bug in
     * the guest or a mode we do not model. Clamp rather than scribble. */
    if (cols != 80 && cols != 40)
        cols = 80;

    if (mode != last_mode || cols != last_cols) {
        /* A geometry change leaves stale pixels from the previous mode, and a
         * 200-row mode does not overwrite bars a previous mode may have used. */
        clear_framebuffers();
        last_mode = mode;
        last_cols = cols;
    }

    /* Text modes only. 0/1 are 40-column, 2/3 are 80-column; the BIOS folds
     * mono modes 2 and 7 to 3 (bios.asm:1080-1083), so mode 7 never appears.
     * Graphics modes 4/5/6 are a separate task -- leave the screen alone rather
     * than rendering text out of a graphics framebuffer. */
    if (mode > 3)
        return;

    blit_text((uint8_t *)lcd_get_active_buffer(), cols);
}
